# Generated by Django 2.0 on 2017-12-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('xanax_used', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('faction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('level', models.IntegerField()),
                ('faction_id', models.IntegerField()),
                ('days_in_faction', models.IntegerField()),
            ],
        ),
    ]
